# tag::system[]
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: system
  labels:
    name: system
spec:
  applicationName: guide-microprofile-config-profile
  applicationImage: system:1.0-SNAPSHOT
  service:
    port: 9443
  expose: true
  route:
    pathType: ImplementationSpecific
  env:
    # tag::default.username[]
    - name: DEFAULT_USERNAME
      valueFrom:
        secretKeyRef:
          # tag::sys-app-credentials-1[]
          name: sys-app-credentials
          # end::sys-app-credentials-1[]
          key: username
    # end::default.username[]
    # tag::default.password[]
    - name: DEFAULT_PASSWORD
      valueFrom:
        secretKeyRef:
          # tag::sys-app-credentials-2[]
          name: sys-app-credentials
          # end::sys-app-credentials-2[]
          key: password
    # end::default.password[]
    # tag::context.root[]
    - name: CONTEXT_ROOT
      value: api/system
    # end::context.root[]
# end::system[]
---
# tag::query[]
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: query
  labels:
    name: query
spec:
  applicationName: guide-microprofile-config-profile
  applicationImage: query:1.0-SNAPSHOT
  service:
    port: 9448
  expose: true
  route:
    pathType: ImplementationSpecific
  env:
    # tag::system.user[]
    - name: SYSTEM_USER
      valueFrom:
        secretKeyRef:
          # tag::sys-app-credentials-3[]
          name: sys-app-credentials
          # end::sys-app-credentials-3[]
          key: username
    # end::system.user[]
    # tag::system.password[]
    - name: SYSTEM_PASSWORD
      valueFrom:
        secretKeyRef:
          # tag::sys-app-credentials-4[]
          name: sys-app-credentials
          # end::sys-app-credentials-4[]
          key: password
    # end::system.password[]
  # tag::system.contextRoot[]
    - name: SYSTEM_CONTEXTROOT
      value: api/system
  # end::system.contextRoot[]
# end::query[]
