# tag::system[]
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: system
  labels:
    name: system
spec:
  applicationImage: system:1.0-SNAPSHOT
  service:
    port: 9080
  expose: true
  route:
    pathType: ImplementationSpecific
  # tag::system.env[]
  env:
    # tag::default.username[]
    - name: DEFAULT_USERNAME
      valueFrom:
        secretKeyRef:
          name: sys-app-credentials
          key: username
    # end::default.username[]
    # tag::default.password[]
    - name: DEFAULT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sys-app-credentials
          key: password
    # end::default.password[]
  # end::system.env[]
# end::system[]
---
# tag::query[]
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: query
  labels:
    name: query
spec:
  applicationImage: query:1.0-SNAPSHOT
  service:
    port: 9085
  expose: true
  route:
    pathType: ImplementationSpecific
  # tag::query.env[]
  env:
    # tag::system.user[]
    - name: SYSTEM_USER
      valueFrom:
        secretKeyRef:
          name: sys-app-credentials
          key: username
    # end::system.user[]
    # tag::system.password[]
    - name: SYSTEM_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sys-app-credentials
          key: password
    # end::system.password[]
  # end::query.env[]
# end::query[]